
# https://github.com/manubot/manubot#process

# output formats to create (Pandoc's --to/--write)
output-formats:
  - html
  - pdf
  - docx
  - jats

# pandoc options (--defaults)
pandoc-options-directory: pandoc-options
# or just use file names
pandoc-options:
  html:
    - common.yaml
    - custom-filters.yaml
    - html.yaml
  docx:
    - common.yaml
    - custom-filters.yaml
    - docx.yaml

# things for include-after-body
themes:
  - default
plugins:
  - anchors
  - accordion
filters:
  - pandoc-fignos
  - pandoc-eqnos
  - pandoc-tablenos
  - pandoc-citeproc

# content
# content-directory: content

# input-files for pandoc
content-files:
  - "content/*.md"
# See why we need to know where images
# are and what is the minimum we need to know
# Can we extract images actually used in content-files
images:
  - content/**/*.[jpg|png]
metadata-file: content/metadata.yaml
bibliography-files:
  - "content/manual-references*.*"
  - content/references.json

cache-directory: content/.cache
# config file is not the right place for this,
# possibly better as CLI option
clear-requests-cache: False
no-requests-cache: False
requests-cache: True

log-level: INFO

# Directory to output files generated by manubot
output-directory: output

variable-files:
  - namespace: my-results
    path: URL
  - namespace: null
    path: path

# think about the different workflows here
webpage:
  checkout: gh-pages
  version: # generated
  timestamp: True
  no-ots-cache: False
  ots-cache: True
  ots-cache: # inherit from cache-directory

